### ISSUE TITLE
TODO: Create start window (load window) and menu window

### ISSUE THREAD

**Issue by tegic** [R4zar0x/sea-battle#6]
Create start window (load window) and menu window.
Maybe, we must add a developers` names at load window window and game name.
At menu window must be buttons "Start game", "Settings", "Exit" (Button "Settings" must not work yet).

**Comment by R4zar0x** [comment]
https://user-images.githubusercontent.com/67277331/187551267-23ec3cd4-9f94-4114-9f53-2e395e51b0cf.mp4
